### ISSUE TITLE
Homework

### ISSUE THREAD

**Issue by Illesgabor** [daroczig/CEU-R-lab#10]
Datacamp question:
Compute the arithmetic mean of the random numbers you generated in the previous exercise.

My solution:
set.seed(42)
x <- mean (runif(15, min = 1, max = 5))
x

Datacamp doesn't accept it. Instruction:
Hint
Use the mean function to compute the arithmetic mean.

I do not know, what is wrong with my code...
Thank you!
Gabor

![image](https://user-images.githubusercontent.com/11815347/30774822-014e642a-a089-11e7-8e73-4856e045a798.png)

**Comment by daroczig** [comment]
The previous exercise was:

```
Generate 15 random numbers between 0 and 5 and store in variable x.
```

Note the min amount :)

FTR you don't have to reassign `x`, it's available from the previous exercise, so assume it's already there -- just apply `mean`
