### ISSUE TITLE
supplementary materials on moodle

### ISSUE THREAD

**Issue by peterduronelly** [daroczig/CEU-R-lab#12]
Gergely,

I have not been able to access Gábor&Gábor's supplementary stuff on data types from moodle. (Tried on Tue and on Wed.) Can you pls check the status of the upload? 

Thx

Peter

**Comment by daroczig** [comment]
Thanks for the report -- can you pls try again and report back if it's not working?

**Comment by peterduronelly** [comment]
It works fine now. Thx.
