### ISSUE TITLE
Question on Week 2, exercise 9 homework

### ISSUE THREAD

**Issue by AdamSanyo88** [daroczig/CEU-R-lab#13]
Dear Gábor,

I have some issues understanding this question in this week's homework:
"The **mtd** object from the previous exercises is still available in your R sessions. Create a new summary data.table object called **mtdgear**, where you count the number of cars (stored in the **cars** column) and the average horsepower (stored in the **avg_hp** column)."

If I understand this exercise correctly, I should create a 3 by 3 data.table with the **gear**, **cars**, and **avg_hp** columns. Could you clarify if I'm on the right track with this approach?

Thanks,
Adam

**Comment by daroczig** [comment]
That's right -- I've just updated the description to reflect that this is to be done by gears:

> The `mtd` object from the previous exercises is still available in your R session. Create a new `data.table` object called `mtdgear`, where you count the number of cars (stored in the `cars` column) and the average horsepower (stored in the `avg_hp` column) per gear.

Please reopen / comment if that's still not clear.
