### ISSUE TITLE
Last problem in Data Camp hwk

### ISSUE THREAD

**Issue by nadezhdagesheva** [daroczig/CEU-R-lab#20]
Dear professor Daroczi,

Would you please clarify what does the condition "Reorder the factor levels in this new object by the related air_time" in the "A complex example" problem exactly means? I tried with the setorder command as a separate step, also with the as.factor() command in the ggplot(..., aes(***)), but there still seems to be an error with the barplot. As a hint from Data Camp I get "Have you tried with factor()?".

Many thanks,
Nadezhda Gesheva

**Comment by daroczig** [comment]
I cannot help more at this time other than suggesting taking that hint seriously and also check my answers at #19 and #21 

Note: if you get stuck and cannot solve it after all, it's ~10% of the overall homework, so not that big deal
