### ISSUE TITLE
Home Assignement Datacamp

### ISSUE THREAD

**Issue by Illesgabor** [daroczig/CEU-R-lab#22]
Hi Gergő,
In the current Datacamp task I found a mistake (I hope it is a mistake and not my misunderstanding...) :
![screen shot 2017-10-18 at 16 28 22](https://user-images.githubusercontent.com/11815347/31724432-f102b0a6-b421-11e7-9ec4-c109885e76f7.png)

In the screenshot you can see, that in the code I used "distance" as the task explained, but it was not accepted by the system. Instead it needed a code:

ggplot (dt, aes(origin, air_time)) + geom_boxplot() + facet_wrap(~carrier)

But the "air_time" was not in the original task.
I hope this was clear.

Gabor

**Comment by daroczig** [comment]
Thanks a lot, good catch -- I've just pushed a fix with replacing "dist" with "air time" in the exercise text.
