### ISSUE TITLE
Week5 new findings

### ISSUE THREAD

**Issue by Illesgabor** [daroczig/CEU-R-lab#25]
Hello Gergő,

on the Datacamp W% I found the followings:

# Another Barplot
There is a mixture in 'cut' and 'color'. The text asks for 'cut' to compute, but the right solution is with 'color'.

#Plotting Summaries
The same problem, but the other way around.

#Plotting Summary Labels
The code with geom_label instead of geom_text is also right (as far as I can judge it). but was not accepted.

Regards,

Gabor

**Comment by daroczig** [comment]
Thanks a lot for catching these problems, I've just pushed a fix for these. I'm doing a final round of QC in the next 2 hours and then will send out the official assignments to everyone in the group.

**Comment by daroczig** [comment]
PS regarding `geom_text` and `geom_label`: there's a small diff, as the latter creates a small box around the text for improved readability -- that's why DataCamp cannot accept either of those. In short, use `geom_text`.
