### ISSUE TITLE
Week4 - A more complex summary

### ISSUE THREAD

**Issue by ghost** [daroczig/CEU-R-lab#26]
Dear Gergely, 

I found the following issue. Two reference for the name of the variable but with different instructions (however the res is the good). As far as I remember there is one more same issue.

Compute the minimum, the (arithmetic) average, the standard deviation and the max of the air time of flights in the dt dataset split by the origin airport, and store **the result in the n variable**! The resulting data.table object should have the following column names: airport, min, avg, stddev and max, **and store it in the res variable.**

Best,
Adam

**Comment by bonnyp** [comment]
Hi Gergely,

There is also a similarly worded question in Week 5: Multiple Summaries.

You can reword this also, as no need to store in n, when result is asking for summaries variable answer.

"Compute the minimum and the maximum prices of diamonds in the dt dataset split by the color, and store the result in the n variable! The resulting data.table object should have the following column names: color, min and max, and store it in the summaries variable."

Thanks.

**Comment by daroczig** [comment]
Thanks a lot, good catch -- both fixed now.
