### ISSUE TITLE
Geom_Text labels question

### ISSUE THREAD

**Issue by bonnyp** [daroczig/CEU-R-lab#28]
What is the difference between adding a label in ggplot() vs in geom_text()?

1.) ggplot(dt, aes(x, y), label=z) + geom_text()
vs
2.) ggplot(dt, aes(x,y)) + geom_text(label=z)

I've seen #2 in google results for geom_text syntax.  One of the questions in Week5 only accepts #1.
Thanks

**Comment by daroczig** [comment]
There's no diff between those two -- whatever you define in the `ggplot` part, will be passed to all geoms. Now that you have only one geom, it's pretty much the same as defining that arg in the geom.

On the other hand, I think neither of (1) or (2) is correct ... The `label` should be defined withing the `aes` call, as you are mapping a variable to the plot.

**Comment by mdemete** [comment]
Hi,
regarding this question, actually I've tried submitting 
ggplot(dt, aes(weight, price)) + geom_text(aes(label=cut))
and the plot was good but DataCamp did not accept it so I was forced to used option   @@1.
![image](https://user-images.githubusercontent.com/29068063/31896151-5652809a-b813-11e7-8905-48f1cebdfbe7.png)

**Comment by daroczig** [comment]
Thanks @mdemete, good point -- unfortunately DataCamp not only checks the resulting image, but the actual call as well, so all the aes should be defined in the `ggplot` call

**Comment by mdemete** [comment]
Thanks!
Melinda
