### ISSUE TITLE
Are points earned with Assignment 5 included in our final score?

### ISSUE THREAD

**Issue by ltagai** [daroczig/CEU-R-lab#29]
Dear Gergő,

Are the points earned with Assignment 5 included in our final score or not?
Also, I don't feel comfortable with the results of the my first homework assignments, is it possible to extra assignments to try and compensate? I also would very much the extra practice. Thanks!
Lilla

**Comment by daroczig** [comment]
> Are the points earned with Assignment 5 included in our final score or not?

Yes.

> Is it possible to extra assignments to try and compensate? 

If the missed homework / quizzes will significantly affect your final grade, we can discuss that. On the other hand, I think missing one homework is not a big deal, as 50% of your final grade is basically based on the exam performance. Anyway, don't worry about the missed homeworks for now, we'll figure out something.
