### ISSUE TITLE
week 5 last task

### ISSUE THREAD

**Issue by kgbgergo** [daroczig/CEU-R-lab#30]
Hi Gergely

I get feedback saying "The contents of the variable dsummary aren't correct. "
My dsummary looks this:
     cut             price
1:  Ideal           3457.542
2:  Good          3928.864
3:  Very Good 3981.760
4:  Fair            4358.758
5:  Premium    4584.258

My plot looks this:
![kep](https://user-images.githubusercontent.com/32012042/31902522-7702632a-b825-11e7-95c4-47b44e8c62ca.png)

Please let me know what I did wrong.
Thanks!

**Comment by daroczig** [comment]
I think you reordered the rows of `dsummary` instead of the factor levels. FTR `dsummary` should look like:

```
> dsummary
         cut    price
1:     Ideal 3457.542
2:   Premium 4584.258
3:      Good 3928.864
4: Very Good 3981.760
5:      Fair 4358.758
> str(dsummary)
Classes ‘data.table’ and 'data.frame':	5 obs. of  2 variables:
 $ cut  : Ord.factor w/ 5 levels "Ideal"<"Good"<..: 1 5 2 3 4
 $ price: num  3458 4584 3929 3982 4359
 - attr(*, ".internal.selfref")=<externalptr> 
```

Let me know if this helps or would you need any further pointers or if you see any issues with the exercise, and I'll reopen the ticket
