### ISSUE TITLE
Case Study on Bisnode Dataset

### ISSUE THREAD

**Issue by foochg** [daroczig/CEU-R-lab#31]
Dear Gergely,
The class notes for week 5 say "Please find the data and R scripts uploaded to Moodle", but I could not locate the files under the course site (Data Analysis 1a: Foundation of Data management in R (Group 2) 2017/2018 Fall). Could you help me how to find them?
Thanks in advance! Best regards,
Laszlo

**Comment by daroczig** [comment]
Thanks for the reminder -- added the URL under "Week 5" in Moodle now, please check again.
