### ISSUE TITLE
Grades

### ISSUE THREAD

**Issue by kgbgergo** [daroczig/CEU-R-lab#33]
Hi Gergely

When can we expect the grades to be published?
Thanks!

Gergely

**Comment by daroczig** [comment]
Good question -- I've shared the grades with the department coordinator, who can record those in Infosys, at the end of October. I reach out to her and will get back to you once I have more information.

**Comment by daroczig** [comment]
Just heard back from the department coordinator -- the grades were recorded in Infosys on Monday, so please check there. If you cannot find it, please contact Eszter Fusch.
