### ISSUE TITLE
Assignment grading

### ISSUE THREAD

**Issue by BenceToth** [daroczig/CEU-R-lab#35]
Hello Gergely,
For the Data Analytics 1 subject, "Assignments (40%) - Seminars" counts towards the final grade.
How do you grade the DataCamp exercises? Is it just the matter of completing or not (100% vs. 0%) or is there another method behind?
Bence

**Comment by daroczig** [comment]
Hi Bence, good question. There's an XP (score) associated with each exercise so the homework is evaluated by the number of scores achieved out of the total, so it's not simply 0% VS 100% but actually checking how many homework exercises you finished -- with or without hint. On the other hand, you can keep retrying all the exercises any number of times ... so actually it will be rather 0% or 100% if someone spends enough time on it. I hope this helps
