### ISSUE TITLE
Data Camp homework

### ISSUE THREAD

**Issue by samatanveer** [daroczig/CEU-R-lab#36]
Q. Do we have to do Data.table novice, Data.table yeoman and Data.table expert for homework due sunday? Because I keep checking hint and was wondering if we can do the submission after Monday's class (by Tuesday for example)? We would have covered more of data.tables that way.

**Comment by daroczig** [comment]
Only the first chapter (Data.table novice) is supposed to be part of the assignment -- the other two chapters are optional and can be finished later. Actually, I'd suggest doing those 2 later :)

**Comment by daroczig** [comment]
![image](https://user-images.githubusercontent.com/495736/46480297-3b419680-c7f1-11e8-9d13-9d931c7129b1.png)

**Comment by samatanveer** [comment]
Hi, perfect. Actually I completed the first chapter and my status was 'Under progress' which caused the confusion. Thank you so much. Its clear now.
