### ISSUE TITLE
DataCamp homework system issue

### ISSUE THREAD

**Issue by BenceToth** [daroczig/CEU-R-lab#37]
Hello,

I cannot run/submit any code for the Week5 homework in DataCamp as the R console shows this error message:
![image](https://user-images.githubusercontent.com/43184996/47020218-310c8a00-d159-11e8-81b0-65333e34a67c.png)

Can you please fix this? I can only do the homework today, I will not be in the country during the deadline.

Thank you,
Bence

**Comment by daroczig** [comment]
I can check later, until then, I'd suggest skipping to the next exercise
then

--
Sent from a mobile phone with an annoying input interface, pls excuse my
brevity/spelling issues.

**Comment by daroczig** [comment]
Hm , this might be a temporary error? I've checked a couple times and seems to work OK.

![image](https://user-images.githubusercontent.com/495736/47026857-ae8ac700-d166-11e8-8373-bd89fcaaea23.png)

can you pls retry at https://campus.datacamp.com/courses/ceu-da1-2018-seminar-homeworks/44547?

**Comment by BenceToth** [comment]
Thank you, with the link provided, I could do it. From the My Assignments menu it still gave an error.

**Comment by daroczig** [comment]
I'm glad it worked :tada: 
No idea what's going in with the Assignment menu, though, but I have no authority there to fix it :(
