### ISSUE TITLE
Problem with Datacamp homework 5

### ISSUE THREAD

**Issue by benedekpasztor** [daroczig/CEU-R-lab#38]
Dear Gergő,

A couple of us experience a problem with the Datacamp homework no. 5.

It says the following error message:

![image](https://user-images.githubusercontent.com/43274088/47086423-b6577380-d219-11e8-89f8-d4eb083e03f2.png)

Could you do something to solve the problem?

Best regards,

Benedek Pásztor

**Comment by daroczig** [comment]
Not sure what's the problem with DataCamp, but as per #37 using the direct URL from the GH repo works. Please confirm.

**Comment by benedekpasztor** [comment]
Yes, thanks, not it works after following the link at #37 .

Benedek

**Comment by daroczig** [comment]
Thanks for the feedback. Note that this is the very same link I included in the readme of the GH repo at https://github.com/daroczig/CEU-R-lab#week-5-100-min-introduction-to-data-visualization
