### ISSUE TITLE
Datacamp hw6 issue

### ISSUE THREAD

**Issue by BenceToth** [daroczig/CEU-R-lab#39]
Dear Gergő,

I cannot submit the last excercise of this week's Datacamp homework.
I tried multiple browsers, using the link in the repo and the assignment tab, same result.

I managed to do everything else, but at the Faceting question, I get an error whenever I try to submit the right anwer. It is quite weird as it functions properly when trying to submit an incorrect answer.
Incorrect:
![image](https://user-images.githubusercontent.com/43184996/47492476-61d17b00-d84d-11e8-8b0e-c627445f38ab.png)
Correct:
![image](https://user-images.githubusercontent.com/43184996/47492514-7d3c8600-d84d-11e8-8454-56951d4e129e.png)

**Comment by daroczig** [comment]
thanks, this was an error in the checks being done on the exercise -- fix pushed, pls check after page reload

**Comment by BenceToth** [comment]
Unfortunately issue is still on.

**Comment by daroczig** [comment]
Sorry, I have no idea what might be the problem :/

Testing this here works, and I see several 100% submissions from the past days. Maybe try in a new browser / incognito window?

If it doesn't work, don't bother, you'll lose a couple points and that's it.

**Comment by BenceToth** [comment]
New browser did not work, fortunately incognito did.
Thanks!
